routes/web.php
<?php

use App\Http\Controllers\backend\AboutController;
use App\Http\Controllers\backend\AgendaController;
use App\Http\Controllers\backend\CategoryController;
use App\Http\Controllers\backend\DashboardController;
use App\Http\Controllers\backend\ArticleController;
use App\Http\Controllers\backend\CatProductController;
use App\Http\Controllers\backend\FaqController;
use App\Http\Controllers\backend\InvoiceController;
use App\Http\Controllers\backend\LinkController;
use App\Http\Controllers\backend\ProductController;
use App\Http\Controllers\backend\ProductImageController;
use App\Http\Controllers\backend\SettingController;
use App\Http\Controllers\backend\SliderController;
use App\Http\Controllers\backend\StaticPageController;
use App\Http\Controllers\backend\TestimonialController;
use App\Http\Controllers\Role\UserController;
use App\Http\Controllers\frontend\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Role\AdminController;
use App\Livewire\DynamicSelect;
use App\Livewire\ShowPosts;
use App\Models\About;
use App\Models\CatProduct;
use App\Models\Invoice;
use App\Models\Static_Page;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::middleware(['auth', 'auth.admin'])->group(function () {
    Route::get('/dropdown', ShowPosts::class);
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('role.admin');
    Route::resource('/categories', CategoryController::class);
    Route::resource('/agenda', AgendaController::class);
    Route::resource('/article', ArticleController::class);
    Route::resource('/faq', FaqController::class);
    Route::resource('/invoice', InvoiceController::class);

    Route::resource('/category-product', CatProductController::class);
    Route::resource('/about', AboutController::class);
    Route::resource('/link', LinkController::class);
    Route::resource('/setting', SettingController::class);
    Route::resource('/slider', SliderController::class);
    Route::resource('/static-page', StaticPageController::class);
    // Pada routes/web.php

    // Route::resource('/account' , UserController::class);
    Route::resource('testimonial', TestimonialController::class);

    Route::group(['prefix' => 'laravel-filemanager'], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });


    // Product Routes

    Route::get('/product', [ProductController::class, 'index'])->name('product');
    Route::get('/product/add', [ProductController::class, 'create'])->name('add_product');
    Route::post('/product/add', [ProductController::class, 'store'])->name('store_product');
    Route::get('/product/{product}/edit', [ProductController::class, 'edit'])->name('edit_product');
    Route::put('/product/{product}', [ProductController::class, 'update'])->name('update_product');
    Route::delete('/product/{id}', [ProductController::class, 'destroy'])->name('delete_product');
    Route::delete('/product/image/{id}', [ProductImageController::class, 'destroy'])->name('destroy');


    // Route::post('/add-to-cart', [CartController::class, 'addCart'])->name('add_to_cart');
    // Route::get('/cart',[CartController::class,'index'])->name('cart.index');
    // Route::post('/cart/store', [CartController::class, 'addToCart'])->name('cart.store');
    // Route::get('/shopping-cart', [HomeController::class, 'bookCart'])->name('shopping.cart');
    // Route::get('/product/{slug}/add', [HomeController::class, 'addProductoCart'])->name('addbook.to.cart');
    // Route::patch('/update-shopping-cart', [HomeController::class, 'updateCart'])->name('update.sopping.cart');
    // Route::delete('/delete-cart-product', [HomeController::class, 'deleteProduct'])->name('delete.cart.product');

});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/my-account', [UserController::class, 'index'])->name('user.index');
    Route::post('/', [CartController::class, 'store'])->name('cart.store');
    Route::post('/cart-details', [CartController::class, 'show'])->name('cart.show');
    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::post('/update-qty/{slug}', [CartController::class, 'updateQty'])->name('up.cart');
    // Route::delete('/drop',[CartController::class,'destroy'])->name('hapus.cart');
    // Route::post('/checkout/{slug}', 'CartController@checkout')->name('checkout');


    Route::delete('/{cartId}', [CartController::class, 'deleteCartItem'])->name('cart.delete');
    Route::get('/cart/items', [CartController::class, 'listAllCartItems'])->name('test');
    Route::delete('/cart/items', [CartController::class, 'deleteAllUserCartItems'])->name('cart.delete.all');
    Route::post('/checkout', [CartController::class, 'checkOut'])->name('checkout');


});

// Guest Homepage
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/', [ProductController::class, 'productHome'])->name('home');
Route::get('/produk/{slug}', [ProductController::class, 'productView'])->name('show');

app/Http/Controllers/backend/AboutController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\AboutRequest;
use App\Http\Requests\UpdateAboutRequest;
use App\Models\About;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $abouts = About::all();

            return DataTables::of($abouts)
                ->addColumn('status', function ($about) {
                    if ($about->status == 0) {
                        return ' <span class="badge bg-info text-dark"><i class="ri-draft-line me-1"></i> Draft</span>';
                    } else {
                        return '<span class="badge bg-success"><i class="ri-bookmark-3-fill me-1"></i> Published</span>';
                    }
                })
                ->addColumn('button', function ($about) {
                    return '
                    <a class="ri-edit-box-line" href="about/' . $about->id . '/edit"></a>
                    <a data-toggle="modal" data-target="#deleteModal" class="delete ri-delete-bin-5-line"  href="#" onclick="deleteAbout(this)" data-id="' . $about->id . ' "></a>
                    ';
                })
                ->rawColumns(['button', 'status'])
                ->make(true);
        }
        return view('backend.about.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('backend.about.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(AboutRequest $request)
    {
        $data = $request->validated();

        if ($request->hasFile('image')) {
            $filename = time() . '_' . $request->image->getClientOriginalName();
            $filePath = $request->image->storeAs('about', $filename);
            $data['image_url'] = $filePath;
        }

        About::create($data);

        return redirect(route('about.index'))->with('success', 'About Telah Dibuat');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $about = About::findOrFail($id);

        return view('backend.about.edit', compact('about'));
    }


    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateAboutRequest $request, string $id)
    {
        $about = About::findOrFail($id);

        $data = $request->validated();
        if ($request->hasFile('image')) {
            $request->validate([
                'image' => ['required', 'max:2028', 'image'],
            ]);

            // Hapus gambar lama jika ada
            if ($about->image_url) {
                Storage::delete($about->image_url);
            }

            // Simpan gambar baru
            $filename = time() . '_' . $request->image->getClientOriginalName();
            $filePath = $request->image->storeAs('about', $filename);
            $data['image_url'] = $filePath;
        }

        $about->update($data);

        return redirect(route('about.index'))->with('success', 'Update tersimpan');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        try {
            $about = About::findOrFail($id);

            if (!empty($about->image_url) && Storage::exists($about->image_url)) {
                Storage::delete($about->image_url);
            }

            $about->delete();
            return response()->json(['success' => true, 'message' => 'Artikel berhasil dihapus.']);
        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return response()->json(['error' => 'Artikel tidak ditemukan.'], 404);
        }
    }
}

app/Http/Controllers/backend/AgendaController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Models\Agenda;
use Illuminate\Http\Request;

class AgendaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('backend.agenda.index', ['agenda' => Agenda::all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/backend/ArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\ArticleRequest;
use App\Http\Requests\UpdateArticleRequest;
use App\Models\Article;
use App\Models\Category;
use Intervention\Image\Facades\Image;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;

use function PHPUnit\Framework\returnSelf;

class ArticleController extends Controller
{

    public function index()
    {
        if (request()->ajax()) {
            $articles = Article::with('category')->where('category_id', '!=', 2)->latest()->get();


            return DataTables::of($articles)
                ->addIndexColumn()
                ->addColumn('category_id', function ($article) {
                    return $article->category->nama;
                })
                ->addColumn('status', function ($article) {
                    if ($article->status == 0) {
                        return ' <span class="badge bg-info text-dark"><i class="ri-draft-line me-1"></i> Draft</span>';
                    } else {
                        return '<span class="badge bg-success"><i class="ri-bookmark-3-fill me-1"></i> Published</span>';
                    }
                })
                ->addColumn('button', function ($article) {
                    return '
                            <a href="article/' . $article->id . '" class="view ri-eye-line"></a>
                            <a class="ri-edit-box-line" href="article/' . $article->id . '/edit"></a>
                            <a data-toggle="modal" data-target="#deleteModal" class="delete ri-delete-bin-5-line" href="#" onclick="deleteArticle(this)" data-id="' . $article->id . ' "></a>
                        ';
                })
                // yang akan ditampilkan
                ->rawColumns(['category_id', 'status', 'button'])
                ->make();
        }

        return view('backend.article.index');
    }



    // membuat article
    public function create()
    {
        return view('backend.article.create', [
            'categories' => Category::get()
        ]);
    }

    public function store(ArticleRequest $request)
    {
        $data = $request->validated();

        $filename = time() . '_' . $request->image->getClientOriginalName();
        $filePath = $request->image->storeAs('uploads', $filename);

        // $img = Image::make('uploads' . $filePath);
        // $img->resize(100, 100);
        // $img->save('uploads/thumbnails', $filename);

        $data['image'] = $filePath;
        $slug = Str::slug($data['title']);
        // $data['thumbnail_image'] = $thumbnailPath;
        $user = auth()->user();
        $data['author'] = $user->name;

        // Valoidasi ketika slugnya ternyata wajib unique/tidak boleh sama
        // disini yang dilakukan bukan menambahkan bilangan uniq dibelakang slugnya, tetapi memang title tersebut tidak dapat diambil
        if (Article::where('slug', $slug)->exists()) {
            return redirect(route('article.create'))->with('error', 'Title already exists. Please change the title.');
        }

        $data['slug'] = $slug;

        Article::create($data);

        return redirect(url('article'))->with('success', 'Article Has Been Created');
    }


    //lihat article
    public function show(string $id)
    {
        return view('backend.article.show', [
            'article' => Article::findOrFail($id)
        ]);

        // $article = Article::findOrFail($id);
    }

    // edit article
    public function edit(string $id)
    {
        return view('backend.article.edit', [
            'article' => Article::findOrFail($id),
            'categories' => Category::get()
        ]);
    }

    // simpan hasil edit ke database
    public function update(UpdateArticleRequest $request, string $id)
    {
        $article = Article::findOrFail($id);

        $data = $request->validated();

        // cek gambar
        if ($request->hasFile('image')) {
            $request->validate([
                'image' => ['required', 'max:2028', 'image'],
            ]);

            // Hapus gambar lama jika ada
            if ($article->image) {
                Storage::delete($article->image);
            }

            // Simpan gambar baru
            $filename = time() . '_' . $request->image->getClientOriginalName();
            $filePath = $request->image->storeAs('uploads', $filename);
            $data['image'] = $filePath;
        }

        $slug = Str::slug($data['title']);

        // Pengecekan/validasi halaman edit
        if (Article::where('slug', $slug)->where('id', '!=', $id)->exists()) {
            return redirect(route('article.edit', ['article' => $id]))->with('error', 'Title sudah ada. Silakan ubah judul.');
        } elseif ($article->slug == $slug) {
            return redirect(route('article.index'))->with('success', 'Data saved');
        }

        // Update the slug in the data array
        $data['slug'] = $slug;

        $data['author'] = auth()->user()->name;

        $article->update($data);

        return redirect(url('article'))->with('success', 'Artikel berhasil diupdate.');
    }



    //hapus
    public function destroy(string $id)
    {
        try {
            $article = Article::findOrFail($id);
            Storage::delete($article->image); // Hapus file gambar jika ada
            $article->delete();
            return response()->json(['success' => true, 'message' => 'Artikel berhasil dihapus.']);
        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return response()->json(['error' => 'Artikel tidak ditemukan.'], 404);
        }
    }
}

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;
use Carbon\Carbon;
use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Http\Request;
use Spatie\FlareClient\View;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard.index', [
            'total_articles' => Article::count(),
            'total_categories' => Category::count(),
            'total_testimonials' => Article::where('category_id', 2)->count(),
            'latest' => Article::with('Category')->whereStatus('1')->latest()->get(),
            'latest_article' => Article::with('Category')->where('category_id', '!=', 2)->latest()->get(),
            
        ]);
    }
}

app/Http/Controllers/backend/ProductImageController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Models\ProductImage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductImageController extends Controller
{
    public function destroy($id)
    {
        $productImage = ProductImage::findOrFail($id);
        Storage::delete($productImage->image);
        $productImage->delete();
        return redirect()->back()->with('success', 'Gambar produk berhasil dihapus');
    }
}

resources/views/backend/testimonial/index.blade.php
@extends('backend.layout.template')

@push('css')
    <link rel="stylesheet" href="{{ asset('assets/css/dataTables.bootstrap5.min.css') }}">
@endpush

@section('content')
    {{-- Content --}}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Testimonial</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ url('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item">Components</li>
                    <li class="breadcrumb-item active">Testimonial</li>
                </ol>
            </nav>
        </div>

        <div class="mt-3">
            <section class="section">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="my-3">
                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                    
                                    @if (session('success'))
                                        <div class="alert alert-success">
                                            {{ session('success') }}
                                        </div>
                                    @endif
                                </div>
                                <a class="btn btn-success" href="{{ route('testimonial.create') }}">Create Testimonial</a>
                                <h5 class="card-title-button">List Article</h5>
                                <table class="table table-bordered datatable" id="dataTable" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Title</th>
                                            <th>Impression</th>
                                            <th>Status</th>
                                            <th>Published Date</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </section>
    </main>
@endsection

@push('js')
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <!-- Vendor JS Files -->
    <script src="{{ asset('assets/vendor/apexcharts/apexcharts.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- Template Main JS File -->
    <script src="{{ asset('assets/js/main.js') }}"></script>

    <script>
        function deleteTestimonial(e) {
            let id = e.getAttribute('data-id');

            if (confirm('Apakah Anda yakin ingin menghapus testimoni ini?')) {
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    type: 'DELETE',
                    url: '/testimonial/' + id,
                    dataType: 'json',
                    success: function(response) {
                        alert(response.message);
                        // Redirect or perform any other actions as needed
                        window.location.href = '/testimonial';
                    },
                    error: function(xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + '\n' + xhr.responseText + '\n' + thrownError);
                    }
                });
            }
        }
    </script>
    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('testimonial.index') }}',
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex'
                    },
                    {
                        data: 'title',
                        name: 'title'
                    },
                    {
                        data: 'impression',
                        name: 'impression',
                        render: function(data, type, row) {
                        var truncatedText = data.split(/\s+/).slice(0, 2).join(' ');
                        return type === 'display' && data.length > 2 ? truncatedText + '...' : data;
                    }
                    },
                    {
                        data: 'status',
                        name: 'status'
                    },
                    {
                        data: 'published_date',
                        name: 'published_date'
                    },
                    {
                        data: 'button',
                        name: 'button'
                    },
                ]
            });
        });
    </script>
@endpush

resources/views/backend/testimonial/show.blade.php
<!-- show.blade.php -->

@extends('backend.layout.template')

@section('title', 'Detail Artikel')
@section('content')
    {{-- Content --}}
    <main class="main" id="main">
        <div class="pagetitle">
            <h1>Testimoni</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ url('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item">Components</li>
                    <li class="breadcrumb-item"><a href="{{ route('testimonial.index') }}">Testimoni</a></li>
                    <li class="breadcrumb-item active">Detail</li>
                </ol>
            </nav>
        </div>

        <div class="card mb-3">
            <div class="card-header">
                <h5 class="card-title">{{ $testimonial->title }}</h5>
            </div>
            <div class="card-body">
                <h5 class="card-text">{{ $testimonial->impression }}</h5>
            </div>
            <div class="card-body">
                <p class="card-text">{!! $testimonial->description !!}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Category: {{ $testimonial->category->nama }}</li>
                <li class="list-group-item">Status: {{ $testimonial->status == 0 ? 'Draft' : 'Published' }}</li>
                <li class="list-group-item">Published Date: {{ $testimonial->published_date }}</li>
            </ul>
            <div class="card-footer">
                <a href="{{ route('testimonial.index') }}" class="btn btn-primary">Back to List</a>
            </div>
        </div>
    </main>
@endsection

@push('js')
    <!-- Vendor JS Files -->
    <script src="{{ asset('assets/vendor/apexcharts/apexcharts.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- Template Main JS File -->
    <script src="{{ asset('assets/js/main.js') }}"></script>
@endpush